version: '3.7'

services:
  app:
    build:
      target: with-postgres-client
    depends_on:
      - postgres12
    environment:
      POSTGRES_PASSWORD: password
    entrypoint: docker-compose/wait-for-postgres.sh postgres12

  postgres12:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: pgmasking_acceptance
