version: '3.7'

services:
  app:
    build:
      target: with-postgres-client
    depends_on:
      - postgres11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: postgres11
    entrypoint: docker-compose/wait-for-postgres.sh postgres11

  postgres11:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: pgmasking_acceptance
