version: '3.7'

services:
  app:
    build:
      target: with-postgres-client
    depends_on:
      - postgres95
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    entrypoint: docker-compose/wait-for-postgres.sh postgres95

  postgres95:
    image: postgres:9.5-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: pgmasking_acceptance
