version: '3.7'

services:
  app:
    build:
      target: with-postgres-client
    depends_on:
      - postgres10
    environment:
      POSTGRES_PASSWORD: password
    entrypoint: docker-compose/wait-for-postgres.sh postgres10

  postgres10:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: pgmasking_acceptance
